import { HardhatRuntimeEnvironment } from "hardhat/types";
import { DeployFunction } from "hardhat-deploy/types";
import * as fs from "fs";
import * as path from "path";

const deployEncryptedReadingPreference: DeployFunction = async function (
  hre: HardhatRuntimeEnvironment
) {
  const { deployer } = await hre.getNamedAccounts();
  const { deploy } = hre.deployments;
  const { network } = hre;

  const deployment = await deploy("EncryptedReadingPreference", {
    from: deployer,
    args: [],
    log: true,
    autoMine: true,
  });

  const contractAddress = deployment.address;
  console.log(`\n✅ EncryptedReadingPreference deployed to: ${contractAddress}`);
  console.log(`📋 Network: ${network.name}`);
  console.log(`👤 Deployer: ${deployer}\n`);

  // Update frontend .env.local file
  try {
    const frontendEnvPath = path.join(__dirname, "../frontend/.env.local");
    const frontendEnvExamplePath = path.join(__dirname, "../frontend/.env.example");

    let envContent = "";

    // Read existing .env.local if it exists
    if (fs.existsSync(frontendEnvPath)) {
      envContent = fs.readFileSync(frontendEnvPath, "utf8");
    } else if (fs.existsSync(frontendEnvExamplePath)) {
      // Use .env.example as template if .env.local doesn't exist
      envContent = fs.readFileSync(frontendEnvExamplePath, "utf8");
    } else {
      // Create new .env.local with contract address
      envContent = `# Contract Address (auto-generated by deployment)\nVITE_CONTRACT_ADDRESS=\n`;
    }

    // Update or add VITE_CONTRACT_ADDRESS
    if (envContent.includes("VITE_CONTRACT_ADDRESS=")) {
      // Replace existing value
      envContent = envContent.replace(
        /VITE_CONTRACT_ADDRESS=.*/,
        `VITE_CONTRACT_ADDRESS=${contractAddress}`
      );
    } else {
      // Add new line if not present
      envContent += `\nVITE_CONTRACT_ADDRESS=${contractAddress}\n`;
    }

    // Ensure frontend directory exists
    const frontendDir = path.join(__dirname, "../frontend");
    if (!fs.existsSync(frontendDir)) {
      fs.mkdirSync(frontendDir, { recursive: true });
    }

    // Write to .env.local
    fs.writeFileSync(frontendEnvPath, envContent);
    console.log(`📝 Contract address saved to: frontend/.env.local`);
    console.log(`   VITE_CONTRACT_ADDRESS=${contractAddress}\n`);
  } catch (error: any) {
    console.warn(`⚠️  Could not update frontend/.env.local: ${error.message}`);
    console.log(`\n📝 Please manually update frontend/.env.local with:`);
    console.log(`   VITE_CONTRACT_ADDRESS=${contractAddress}\n`);
  }


  // Also save to deployments directory for reference
  try {
    const deploymentsDir = path.join(__dirname, `../deployments/${network.name}`);
    if (!fs.existsSync(deploymentsDir)) {
      fs.mkdirSync(deploymentsDir, { recursive: true });
    }

    const deploymentInfo = {
      network: network.name,
      contractAddress: contractAddress,
      deployer: deployer,
      transactionHash: deployment.transactionHash || "",
      deployedAt: new Date().toISOString(),
      chainId: network.config.chainId,
    };

    const deploymentFilePath = path.join(
      deploymentsDir,
      "EncryptedReadingPreference.json"
    );
    fs.writeFileSync(
      deploymentFilePath,
      JSON.stringify(deploymentInfo, null, 2)
    );
    console.log(`📁 Deployment info saved to: deployments/${network.name}/EncryptedReadingPreference.json`);
  } catch (error: any) {
    console.warn(`⚠️  Could not save deployment info: ${error.message}`);
  }

  // Display summary
  console.log("\n" + "=".repeat(60));
  console.log("🎉 DEPLOYMENT COMPLETED SUCCESSFULLY!");
  console.log("=".repeat(60));
  console.log(`📋 Contract: EncryptedReadingPreference`);
  console.log(`📍 Address: ${contractAddress}`);
  console.log(`🌐 Network: ${network.name}`);
  if (network.name !== "hardhat" && network.name !== "localhost") {
    console.log(`🔍 View on Etherscan: https://${network.name === "sepolia" ? "sepolia." : ""}etherscan.io/address/${contractAddress}`);
  }
  console.log("=".repeat(60) + "\n");
};

export default deployEncryptedReadingPreference;

deployEncryptedReadingPreference.tags = ["EncryptedReadingPreference"];

